# Generated by Django 5.0.1 on 2025-11-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, default='', max_length=255)),
                ('duration_seconds', models.IntegerField()),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('cover_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title', 'artist'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('position', models.FloatField(help_text='Fractional position for ordering')),
                ('votes', models.IntegerField(default=0)),
                ('added_by', models.CharField(default='Anonymous', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_playing', models.BooleanField(default=False)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='playlist.track')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
